# yaml-language-server: $schema=https://raw.githubusercontent.com/apollographql/router/main/apollo-router/src/configuration/testdata/schema/v2.7.json

supergraph:
  listen: 127.0.0.1:4000
  introspection: true

# Propagate all incoming headers to subgraphs
headers:
  all:
    request:
      - propagate:
          matching: .*

# Allow local Explorer and client dev server to query the router
cors:
  origins:
    - http://localhost:3000
    - https://studio.apollographql.com

# Enable sandbox in development
sandbox:
  enabled: true

# Disable homepage (conflicts with sandbox)
homepage:
  enabled: false

include_subgraph_errors:
  all: true
