federation_version: =2.9.0

subgraphs:
  products:
    routing_url: http://localhost:4001/products/graphql
    schema:
      file: ../subgraphs/products/schema.graphql

  orders:
    routing_url: http://localhost:4001/orders/graphql
    schema:
      file: ../subgraphs/orders/schema.graphql
